### PR TITLE
Use the official API instead of scraping the page

### PR DESCRIPTION
**Pull request by yefim**
I've just released an API for Diverse UI. Feel free to read [the docs](https://github.com/reneepadgham/diverseui#api).

### CODE REVIEW

**Review by samcus — CHANGES_REQUESTED** [review]
Thanks for making the api now instead of just having a JS object. But the purpose of getRandom is to request a random person with the option of restricting to male or female. It should return a single person. Your PR makes getRandom the same as getAll.

**Comment by samcus** [comment]
@yefim Are you able to extend your API to allow for?: 
GET a random 
GET a random :gender
GET a specific :id or :slug

if not I can manipulate the data on my end

**Comment by yefim** [comment]
@samcus sorry for the confusion. Didn't realize `getRandom` only returned one. Will update my PR.

**Comment by samcus** [comment]
@yefim Thanks! Sorry for the confusion, feel free to change the names of the methods if you have an idea to make it more clear. I'm open to changes such as that.

**Comment by yefim** [comment]
@samcus I've updated the PR. Please re-review

**Review by samcus — APPROVED** [review]

**Pull request merged**
